{% set name = "addict" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/addict-{{ version }}.tar.gz
  sha256: b3b2210e0e067a281f5646c8c5db92e99b7231ea8b0eb5f74dbdf9e259d4e494

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps and --no-build-isolation
  skip: True # [not linux64]

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - addict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mewwts/addict
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/mewwts/addict
  doc_url: https://github.com/mewwts/addict
  summary: Addict is a dictionary whose items can be set using both attribute and item syntax.
  description: a Python module that gives you dictionaries whose values are both gettable and settable using attributes, in addition to standard item-syntax.

extra:
  skip-lints:
    - missing_source
    - avoid_noarch

  services:
    recipe-maintainers:
       - bkreider
    comment: "https://anaconda.zendesk.com/agent/tickets/49247"

