{% set version = "2.1.0" %}
{% set sha256 = "05d7d9d19692377fc0a699d8797466e6284b966f6f3316fc38a815fffcc14416" %}

package:
  name: addict
  version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/mewwts/addict/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - addict

about:
  home: https://github.com/mewwts/addict
  license: MIT
  summary: 'Addict is a dictionary whose items can be set using both attribute and item syntax.'

extra:
  recipe-maintainers:
    - Ohjeah
