travis:
  secure:
    BINSTAR_TOKEN: GPn13pVW1h38qce09ofd55qMDGSqp/nGgCQdEaZOCIPx3uYjLtIYii0n8UOV7bXzzqvCohlO3oLo6jlKpupfVmNPgKaUDOO/4LOBlgbZv5o7Vs8IG+tlLcDgKjF9SfHi2QDtvJqAO2SDxVhEwHfBr650P4svFkdmBvJTnQoQthqbFlvuJ7UKZtkzR3T1mv9COTLMLSWEjmv+BkVmQkoOugbQtVV1pAfIEwsmmCNl1DLAyuN6zg6yMMn3AyM8cSko09zxbwHXqGCZlyyy0/rwcDvKwWFd564F6TL6eF93DhfbBrva5JOOMRHeoHUIE2StAwqddStTxU57bgYEU/kXdp6QtWOglWezQs4S3sWiasfYRSqP9d851GiRbDy8gf/CcG6cmSH9m7u+JuDaZ/z39ZtD8OMvDJKEBF8AC5lfeWUppo6mXSxoppUPuDr9R1h9VFcd/zi5Dh53XlRym1fAeZxC74PyoqqHf9WbRoZIEKhhIRTQ1gXxbAT6Sv9xii3CCYGHTfhkCP0ndSR378/UCnqNT0Ti1yxi5Rn4IC8Y76Uvj/DwUF5coDAu8nafeWTIHFSbwy8mWTI+Vs3+OW2KAeC9gvCbPxxr8gktCoVT3MUyIAm5atfPBkp8m7us3nukLuJRfqO0+fpDOhNve0JQvOH/Nqu+3cUT/iGiUs0CocU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
